meeting_4/rubothub/config/routes.rb
Rails.application.routes.draw do

  root 'home#show'

  get '/login' => 'login#new'
  post '/login' => 'login#create'
  get '/signup' => 'session#new'
  post '/signup' => 'session#create'
  resources :users, only: [ :edit, :show, :update ] do
    resources :projects, only: [:create]
  end

  resources :projects, only: [ :edit, :show, :update ]
end

meeting_4/rubothub/app/models/project.rb
class Project < ActiveRecord::Base
  has_many :projects_users, inverse_of: :project, dependent: :destroy
  has_many :users, :through => :projects_users

  validates :title, presence: true
  validates :description, presence: true
end

meeting_4/rubothub/app/models/projects_user.rb
class ProjectsUser < ActiveRecord::Base
  validates :user, presence: true
  validates :project, presence: true

  belongs_to :user, inverse_of: :projects_users
  belongs_to :project, inverse_of: :projects_users
end

meeting_4/rubothub/app/models/user.rb
class User < ActiveRecord::Base
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
  validates :password, presence: true, on: :create
  validates :password,
    format: { with: /^(?=.*[a-zA-Z])(?=.*[0-9]).{8,}$/, multiline: true },
    allow_blank: true

  has_many :user_projects, inverse_of: :user, dependent: :destroy
  has_many :projects, through: :user_projects
end

meeting_4/rubothub/app/models/user_project.rb
class UserProject < ActiveRecord::Base
  validates :user, presence: true
  validates :project, presence: true
  
  belongs_to :user, inverse_of: :user_projects
  belongs_to :project, inverse_of: :user_projects
end

meeting_4/rubothub/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :current_user

  private 
  	def current_user
  		id = session[:current_user_id]
  		@current_user = User.find_by(id: id)
  	end
end

meeting_4/rubothub/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show

  end
end

meeting_4/rubothub/app/controllers/login_controller.rb
class LoginController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.find_by(email: user_params[:email], password: user_params[:password])

  	if (@user.present?)
		redirect_to :root, notice: 'Successfully logged in'
  	else
  		@user = User.new user_params
		@user.errors.add :email, 'Invalid credentials'
		render :new
  	end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

meeting_4/rubothub/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def new

  end

  def create
    @user = User.find params[:user_id]
    if (@user.present?)

      @project = @user.projects.build(project_params)
      if (@project.save)
        redirect_to project_path(@project)
      else
        render "users/edit"
      end
    end
  end

  def edit
    @project = Project.find params[:id]
  end

  def show
    @project = Project.find params[:id]
  end

  def update
    @project = @current_user

    redirect_to(login_path) and return unless @project.present?

    if @project.update_attributes(project_params)
      redirect_to project_path @project
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private 
    def project_params
      params.require(:project).permit(:title, :description)
    end
end

meeting_4/rubothub/app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to user_path(@user), notice: 'Thanks for signing up!'
    else
      alert_string = 'Could not complete registration. Please fix the errors below'
      flash.now.alert = alert_string
      render 'new', status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end
end

meeting_4/rubothub/app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if passwords_match
      if @user.save
        session[:current_user_id] = @user.id
        flash.notice = "Success"
        redirect_to user_path @user
      else
        render :new
      end
    else
      flash.alert ="Password dont match"
      render :new
    end
  end

  def passwords_match
    params[:user][:password_confirm] == params[:user][:password]
  end

private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end
end

meeting_4/rubothub/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def destroy
    session[:user_id] = nil

    redirect_to root_path
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if params[:user][:password] == params[:user][:password_confirmation]
      if @user.save
        session[:user_id] = @user.id

        redirect_to root_path, notice: 'Successfully Signed up!'
      else
        render :new
      end
    else
      flash.now[:alert] = 'Passwords do not match.'

      render :new
    end
  end

  private
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password)
    end
end

meeting_4/rubothub/app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action(:check_user, only: [:edit])

  def edit
    @user = User.find params[:id]

    @project = @user.projects.build
  end

  def show
    @user = User.find params[:id]
  end

  def update
    @user = @current_user

    redirect_to(login_path) and return unless @user.present?

    if @user.update_attributes(user_params)
      redirect_to user_path @user
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private
  def check_user
    redirect_to login_path unless params[:id] == @current_user.try(:id).to_s
  end


  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end
end

meeting_4/rubothub/app/helpers/application_helper.rb
module ApplicationHelper
end

meeting_4/rubothub/app/helpers/login_helper.rb
module LoginHelper
end

meeting_4/rubothub/app/helpers/project_helper.rb
module ProjectHelper
end

meeting_4/rubothub/app/helpers/projects_helper.rb
module ProjectsHelper
end

meeting_4/rubothub/app/helpers/signup_helper.rb
module SignupHelper
end

meeting_4/rubothub/app/helpers/users_helper.rb
module UsersHelper
end

meeting_4/rubothub/app/views/home/show.html.erb
<div class="panel">
  <h2>Welcome to Rubtohub</h2>
  <p>The online portal for project management</p>
</div>

meeting_4/rubothub/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : 'Rubothub' %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

  <%= render 'shared/top_nav' %>

  <%= render 'shared/flash' %>

  <div class="row">
    <div class="small-12 columns">
      <%= yield %>
    </div>
  </div>

  </body>
</html>

meeting_4/rubothub/app/views/login/new.html.erb
<h2>Log In</h2>
<%= form_for @user, url: login_path do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.text_field :email, :placeholder => :email %>
  <%= f.password_field :password, :placeholder => :password %>
  <%= f.submit "Log In" %>
<% end %>

meeting_4/rubothub/app/views/login/show.html.erb
<h2>Login here<h2>

meeting_4/rubothub/app/views/projects/edit.html.erb
<h2>Edit Project</h2>

<%= form_for @project do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@project.errors.count, "error") %> prohibited
        this project from being saved:
      </h2>
      <ul>
        <% @project.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.text_field :title, :placeholder => :title %>
  <%= f.text_field :description, :placeholder => :description %>
  <%= f.submit "Update" %>
<% end %>

meeting_4/rubothub/app/views/projects/new.html.erb
<h2>New Project</h2>
<%= form_for @project, url: {action: "create"}  do |f| %>
  <%= f.text_field :title, :placeholder => :title %>
  <%= f.text_field :description, :placeholder => :description %>

  <%= f.submit "Create" %>
<% end %>



<!-- <%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user.errors.count, "error") %> prohibited
        this user from being saved:
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.text_field :first_name, :placeholder => :first_name %>
  <%= f.text_field :last_name, :placeholder => :last_name %>
  <%= f.email_field :email, :placeholder => :email %>
  <%= f.password_field :password, :placeholder => :password %>
  <%= f.password_field :password_confirmation, :placeholder => :password_confirmation %>
  <%= f.submit "Update" %>
<% end %> -->

meeting_4/rubothub/app/views/projects/show.html.erb
<div>
	<h1><%= @project.title %></h1>
	<h2><%= @project.description %><h2>
		<div>
			<h3>Users in this project</h3>
			<% @project.users.each do |u| %>
			  <h3><%= link_to "#{u.first_name} #{u.last_name}", user_path(u) %></h3>
			<% end %>
		</div>
</div>

meeting_4/rubothub/app/views/session/new.html.erb
<h2>Signup here</h2>
<% if @user.errors.present? %>
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @user, url: signup_path do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>

  <%= f.label :last_name %>
  <%= f.text_field :last_name %>

  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confim %>
  <%= f.password_field :password_confirm %>

  <%= f.submit %>
<% end %>

meeting_4/rubothub/app/views/shared/_flash.html.erb
<% flash_keys = {notice: 'info', alert: 'warning'} %>
<% flash.each do |key, value| %>
  <div class="alert-box <%= flash_keys.fetch(key, key) %> radius">
    <%= value %>
  </div>
<% end %>

meeting_4/rubothub/app/views/shared/_top_nav.html.erb
<nav class="top-bar">
  <section class="top-bar-section">
    <ul class="left">
      <li><%= link_to 'Rubothub', root_path %></li>
    </ul>
    <% if current_user.present? %>
      <ul class="right">
        <li class="welcome-message"><%= link_to 'Welcome ' + current_user.first_name, user_path(current_user) %></li>
        <li><%= link_to 'Log Out', logout_path %></li>
      </ul>
    <% else %>
      <ul class="right">
        <li><%= link_to 'Login', login_path %></li>
        <li><%= link_to 'Signup', new_session_path %></li>
      </ul>
    <% end %>
  </section>
</nav>

meeting_4/rubothub/app/views/users/edit.html.erb
<h2>Edit User</h2>
<% if @user.errors.present? %>
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @user do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>

  <%= f.label :last_name %>
  <%= f.text_field :last_name %>

  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confim %>
  <%= f.password_field :password_confirm %>

  <%= f.submit %>
<% end %>

<%= form_for @project, url: user_projects_path(@user) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.submit %>
<% end %>

meeting_4/rubothub/app/views/users/show.html.erb
<h2>User</h2>

<p>First Name: <%= @user.first_name %></p>
<p>Last Name: <%= @user.last_name %></p>
<p>Email: <%= @user.email %></p>

<%= link_to 'Edit', edit_user_path %>

<h3>Projects</h3>
<%= link_to 'Add', new_user_project_path(@user) %>
<ul>
  <% @user.projects.each do |project| %>
    <li>
      <p>
        <%= project.title %> - <%= link_to 'View', project_path(project) %>
      </p>
      <p>
        <%= project.description %>
      </p>
    </li>
  <% end %>
</ul>